version: '3.6'

services:
  backend:
    build:
      context: backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/TrackYourTime?schema=public"
      JWT_ACCESS_SECRET: exampleSecret123456789ThisIsTotallySecureTrustMeBroAccess
      JWT_REFRESH_SECRET: exampleSecret123456789ThisIsTotallySecureTrustMeBroRefresh

  frontend:
    build:
      context: frontend
    ports:
      - "8080:80"

  database:
    image: postgres:14.3-alpine3.16
    environment:
      POSTGRES_DB: TrackYourTime
      POSTGRES_PASSWORD: postgres
    volumes:
      - database-storage:/var/lib/postgresql/data

volumes:
  database-storage:
