/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * TrackYourTime
 * OpenAPI spec version: 1.0.0
 */

export interface GetProjectDto {
  id: string;
  name: string;
  hourlyRate: number;
  customer?: string;
  isActive: boolean;
}
