/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * TrackYourTime
 * OpenAPI spec version: 1.0.0
 */

export interface GetUserDto {
  id: string;
  email: string;
  name: string;
  surname: string;
  company: string;
  logo: string;
}
