/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * TrackYourTime
 * OpenAPI spec version: 1.0.0
 */
import axios, { AxiosRequestConfig, AxiosResponse } from "axios";
import type { LoginResponseDto, AuthControllerLoginParams } from ".././model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Generates an access token for the provided user
 */
export const authControllerLogin = (
  params?: AuthControllerLoginParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<LoginResponseDto>> => {
  return axios.post(`/auth/login`, undefined, {
    params,
    ...options,
  });
};
